# -*- coding: utf-8 -*-
"""model_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYB9AGzUC3oIpRGGDPFYNKmUT_ut2dZF
"""

from google.colab import drive
drive.mount('/content/drive')

from tensorflow import keras
from tensorflow.keras.utils import plot_model

model = keras.models.load_model('/content/drive/My Drive/636project/model_improved_lstm.h5')

plot_model(model, show_shapes=True, to_file='lstm_model.png')

model = keras.models.load_model('/content/drive/My Drive/636project/model_improved_cnn.h5')

plot_model(model, show_shapes=True, to_file='cnn_model.png')

prediction = []

for i in range(len(cnn_probality)):
  p = cnn_probality[i] * 0.5 + lstm_probality[i] * 0.5